### ISSUE TITLE
Deprecation

### ISSUE THREAD

**Issue by BillWSY** [CogRob/fetch_and_echo#1]
This might be no longer useful since we have our new infrastructure. Let's keep it for a few days and deprecate it by mid-November unless otherwise needed.

**Comment by zephirefaith** [comment]
No, yeah I agree. Let's however build a wiki which can even be just as simple as pointing to the right resources for building a new skill again, in case we go the long way with this and get new lab members. I can turn this info into a "Quick Start Echo Guide" and deprecate the repo then. Also a good starting point to keep a documentation of the architecture, we can all contribute to it and @BillWSY can correct us wherever necessary, as the main implementer.

**Comment by BillWSY** [comment]
We can transform this repo to a wiki page, and our future members can use this to get their hands wet without having to use (although they should) our infrastructure.

**Comment by zephirefaith** [comment]
I was actually thinking of linking this up with our infrastructure. So like a primer on:
1. Creating Amazon Alexa Skills models
2. Using Flask-ask for interfacing
3. Using ROS-Portal for interfacing with the robot
4. Overview of our complete architecture

But all of this with only one skill, which can be dancing. This way noobs can get their hands wet and also will know the rough gist of the architecture without it getting too complicated. And rather than turning this repo into a wiki, I am thinking of adding all the info to the main wiki repo. It can get confusing with multiple documentation points.

**Comment by BillWSY** [comment]
That sounds a great idea. We can create a minimal tutorial that let future students use our infrastructure to interact with both workspace and cogrob_ros. Meanwhile, the attack surface is not too big, so they wouldn't be overwhelmed.

By transforming into a wiki page I meant a wiki page in the workspace.

Actually, this has been in my mind for a while. Maybe we should do this together so that my familiarity with the arch wouldn't lead to a brief paragraph that is too hard for a beginner.

**Comment by zephirefaith** [comment]
Oh yeah definitely! I am going to close this issue and the one on ros_portal_proto, create a new issue in Workspace repo and link it to the wiki page where we can all contribute. Issue is just for creating one central discussion thread for that wiki.
